version: '3.8'

volumes:
  db_data: { }
  db_data_backups: { }

services:
  app:
    build: .
    volumes:
      - "./db:/wd/db:rw"
    ports:
      - "8000:8000"
    restart: on-failure
    env_file:
      - ./.env
    command: '/start.sh'

  postgres:
    build:
      context: ./docker/db/

    volumes:
      - db_data:/var/lib/postgresql/data
      - db_data_backups:/backups

    env_file:
      - ./.env
    restart: on-failure