# Generated by Django 4.0.5 on 2022-07-17 09:10

import apps.humans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humans", "0001_squashed_0002_remove_human_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="human",
            name="avatar",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to=apps.humans.models.get_icon_path, verbose_name="Avatar"
            ),
        ),
    ]
