# Generated by Django 4.0.5 on 2022-06-23 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('humans', '0003_color_human_favourite_color_by_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='favourite_color_many_to_many',
            field=models.ManyToManyField(related_name='humans_related_by_many_to_many', to='humans.color'),
        ),
        migrations.AlterField(
            model_name='human',
            name='favourite_color_by_foreign_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='humans_related_by_foreign_key', to='humans.color'),
        ),
    ]
